# Generated by Django 5.2.17 on 2026-08-30 02:26

import django.core.validators
import django.db.models.deletion
import spatial_fabric.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_seed_core_privileges'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareGrant',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('resource_kind', models.CharField(help_text='跨模块稳定 namespaced key；不是具体 Provider/GIS 服务类型。', max_length=160, validators=[django.core.validators.RegexValidator(message='resource_kind 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='资源类型键')),
                ('resource_id', models.UUIDField(verbose_name='资源 ID')),
                ('grantee_type', models.CharField(choices=[('PRINCIPAL', '主体'), ('GROUP', '权限组')], max_length=16, verbose_name='被分享主体类型')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='B2.2 只保留 schema-validated 的低复杂度扩展位；ShareGrantResolver 对非空条件默认 fail closed，复杂条件由 Policy evaluator 处理。', verbose_name='附加条件')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_share_grants', to='iam.principal', verbose_name='授权主体')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='share_grants', to='iam.group', verbose_name='被分享权限组')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_share_grants', to='iam.principal', verbose_name='被分享主体')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_share_grants', to='iam.principal', verbose_name='撤销主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_grants', to='tenancy.tenant', verbose_name='资源所属租户')),
            ],
            options={
                'verbose_name': '资源分享授权',
                'verbose_name_plural': '资源分享授权',
                'db_table': 'sf_share_grant',
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('resource_kind', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='resource_kind 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='资源类型键')),
                ('resource_id', models.UUIDField(verbose_name='资源 ID')),
                ('justification', models.TextField(blank=True, verbose_name='申请理由')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('FULFILLED', '已满足'), ('REJECTED', '已拒绝'), ('CANCELLED', '已撤回'), ('EXPIRED', '已过期')], default='PENDING', max_length=16, verbose_name='状态')),
                ('requested_valid_until', models.DateTimeField(blank=True, help_text='为空表示未指定；真正允许的最长时长仍由 Policy/Quota/治理规则限制。', null=True, verbose_name='期望授权失效时间')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_access_requests', to='iam.principal', verbose_name='处理主体')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='iam.principal', verbose_name='请求主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='tenancy.tenant', verbose_name='资源所属租户')),
                ('fulfilled_by_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_access_requests', to='sharing.sharegrant', verbose_name='满足请求的 ShareGrant')),
            ],
            options={
                'verbose_name': '资源访问请求',
                'verbose_name_plural': '资源访问请求',
                'db_table': 'sf_access_request',
            },
        ),
        migrations.CreateModel(
            name='ShareGrantPrivilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privilege_links', to='sharing.sharegrant', verbose_name='资源分享授权')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_grant_links', to='iam.privilege', verbose_name='权限动作')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_grant_privileges', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '资源分享权限',
                'verbose_name_plural': '资源分享权限',
                'db_table': 'sf_share_grant_privilege',
            },
        ),
        migrations.CreateModel(
            name='AccessRequestPrivilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privilege_links', to='sharing.accessrequest', verbose_name='资源访问请求')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_request_links', to='iam.privilege', verbose_name='请求权限动作')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_request_privileges', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '访问请求权限',
                'verbose_name_plural': '访问请求权限',
                'db_table': 'sf_access_request_privilege',
                'indexes': [models.Index(fields=['tenant', 'access_request'], name='sf_accessreqpriv_req_idx'), models.Index(fields=['privilege'], name='sf_accessreqpriv_priv_idx')],
                'constraints': [models.UniqueConstraint(fields=('access_request', 'privilege'), name='sf_accessreqpriv_req_priv_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='sharegrant',
            index=models.Index(fields=['tenant', 'resource_kind', 'resource_id', 'status'], name='sf_share_resource_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sharegrant',
            index=models.Index(fields=['tenant', 'principal', 'status'], name='sf_share_princ_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sharegrant',
            index=models.Index(fields=['tenant', 'group', 'status'], name='sf_share_group_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grantee_type', 'PRINCIPAL'), ('group__isnull', True), ('principal__isnull', False)), models.Q(('grantee_type', 'GROUP'), ('group__isnull', False), ('principal__isnull', True)), _connector='OR'), name='sf_share_grantee_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='sharegrant',
            constraint=models.CheckConstraint(condition=models.Q(('resource_kind', ''), _negated=True), name='sf_share_resource_kind_ck'),
        ),
        migrations.AddConstraint(
            model_name='sharegrant',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_share_valid_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='sharegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='sf_share_revoke_shape_ck'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['tenant', 'requester', 'status'], name='sf_accessreq_requester_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['tenant', 'resource_kind', 'resource_id', 'status'], name='sf_accessreq_resource_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(condition=models.Q(('resource_kind', ''), _negated=True), name='sf_accessreq_resource_kind_ck'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('fulfilled_by_grant__isnull', True), ('status', 'PENDING')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('fulfilled_by_grant__isnull', False), ('status', 'FULFILLED')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('fulfilled_by_grant__isnull', True), ('status__in', ['REJECTED', 'CANCELLED'])), models.Q(('decided_at__isnull', False), ('fulfilled_by_grant__isnull', True), ('status', 'EXPIRED')), _connector='OR'), name='sf_accessreq_status_shape_ck'),
        ),
        migrations.AddIndex(
            model_name='sharegrantprivilege',
            index=models.Index(fields=['tenant', 'grant'], name='sf_sharepriv_grant_idx'),
        ),
        migrations.AddIndex(
            model_name='sharegrantprivilege',
            index=models.Index(fields=['privilege'], name='sf_sharepriv_priv_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharegrantprivilege',
            constraint=models.UniqueConstraint(fields=('grant', 'privilege'), name='sf_sharepriv_grant_priv_uniq'),
        ),
    ]
