# Generated by Django 5.2.17 on 2026-08-30 01:35

import django.db.models.deletion
import spatial_fabric.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_seed_core_privileges'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDefinition',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('key', models.CharField(max_length=160, verbose_name='策略键')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('DEPRECATED', '已弃用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统管理')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_policy_definitions', to='iam.principal', verbose_name='创建主体')),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL 表示平台策略；非 NULL 表示 Tenant 自定义策略。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_definitions', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '策略定义',
                'verbose_name_plural': '策略定义',
                'db_table': 'sf_policy_definition',
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_seq', models.PositiveBigIntegerField(verbose_name='版本序号')),
                ('schema_version', models.CharField(default='1', max_length=40, verbose_name='策略 Schema 版本')),
                ('spec', models.JSONField(default=dict, verbose_name='策略规范')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='内容指纹')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('RETIRED', '已退役')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_policy_versions', to='iam.principal', verbose_name='创建主体')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='governance.policydefinition', verbose_name='策略定义')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_policy_versions', to='iam.principal', verbose_name='发布主体')),
            ],
            options={
                'verbose_name': '策略版本',
                'verbose_name_plural': '策略版本',
                'db_table': 'sf_policy_version',
            },
        ),
        migrations.CreateModel(
            name='PolicyAttachment',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('subject_type', models.CharField(choices=[('ALL', '租户内全部主体'), ('PRINCIPAL', '指定主体'), ('GROUP', '指定组'), ('ROLE', '指定角色')], default='ALL', max_length=16, verbose_name='主体类型')),
                ('target_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境'), ('RESOURCE', '具体资源')], max_length=16, verbose_name='目标类型')),
                ('resource_kind', models.CharField(blank=True, default='', help_text='跨模块稳定 namespaced key；存在性由 ResourceResolver 校验，不是万能资源表。', max_length=160, verbose_name='资源类型键')),
                ('resource_id', models.UUIDField(blank=True, null=True, verbose_name='资源 ID')),
                ('priority', models.IntegerField(default=100, help_text='数值仅用于同层稳定排序；DENY/REQUIRE_APPROVAL/ALLOW 的安全优先级由 evaluator 定义。', verbose_name='优先级')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_policy_attachments', to='iam.principal', verbose_name='绑定主体')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_attachments', to='tenancy.environment', verbose_name='环境目标')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_attachments', to='iam.group', verbose_name='指定组')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_attachments', to='iam.principal', verbose_name='指定主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_attachments', to='tenancy.project', verbose_name='项目目标')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_attachments', to='iam.roledefinition', verbose_name='指定角色')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_attachments', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_attachments', to='tenancy.workspace', verbose_name='工作空间目标')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='governance.policyversion', verbose_name='策略版本')),
            ],
            options={
                'verbose_name': '策略绑定',
                'verbose_name_plural': '策略绑定',
                'db_table': 'sf_policy_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='policydefinition',
            index=models.Index(fields=['tenant', 'status'], name='sf_policy_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='policydefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('key',), name='sf_policy_platform_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='policydefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'key'), name='sf_policy_tenant_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['policy', 'status'], name='sf_policyver_policy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['status', 'published_at'], name='sf_policyver_publish_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version_seq'), name='sf_policyver_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('published_by__isnull', True), ('status', 'DRAFT')), models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status__in', ['PUBLISHED', 'RETIRED'])), _connector='OR'), name='sf_policyver_publish_shape_ck'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['tenant', 'status'], name='sf_pattach_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['principal', 'status'], name='sf_pattach_princ_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['group', 'status'], name='sf_pattach_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['role', 'status'], name='sf_pattach_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['workspace', 'status'], name='sf_pattach_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['project', 'status'], name='sf_pattach_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['environment', 'status'], name='sf_pattach_env_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyattachment',
            index=models.Index(fields=['tenant', 'resource_kind', 'resource_id', 'status'], name='sf_pattach_resource_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('principal__isnull', True), ('role__isnull', True), ('subject_type', 'ALL')), models.Q(('group__isnull', True), ('principal__isnull', False), ('role__isnull', True), ('subject_type', 'PRINCIPAL')), models.Q(('group__isnull', False), ('principal__isnull', True), ('role__isnull', True), ('subject_type', 'GROUP')), models.Q(('group__isnull', True), ('principal__isnull', True), ('role__isnull', False), ('subject_type', 'ROLE')), _connector='OR'), name='sf_policyattach_subject_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='policyattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'ENVIRONMENT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('resource_id__isnull', False), ('target_type', 'RESOURCE'), ('workspace__isnull', True), models.Q(('resource_kind', ''), _negated=True)), _connector='OR'), name='sf_policyattach_target_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='policyattachment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_policyattach_valid_window_ck'),
        ),
    ]
