# Generated by Django 5.2.17 on 2026-08-30 07:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import spatial_fabric.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_seed_core_privileges'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('purpose', models.CharField(choices=[('HIGH_RISK_ACTION', '高风险动作'), ('JIT_ELEVATION', '即时临时提升'), ('BREAK_GLASS_REVIEW', '紧急访问复核'), ('DELEGATION', '委托审批')], max_length=24, verbose_name='审批目的')),
                ('target_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境'), ('RESOURCE', '资源')], max_length=16, verbose_name='目标类型')),
                ('resource_kind', models.CharField(blank=True, default='', max_length=160, validators=[django.core.validators.RegexValidator(message='resource_kind 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='资源类型键')),
                ('resource_id', models.UUIDField(blank=True, null=True, verbose_name='资源 ID')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('CANCELLED', '已撤回')], default='PENDING', max_length=16, verbose_name='状态')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('expires_at', models.DateTimeField(verbose_name='审批证据失效时间')),
                ('requested_valid_until', models.DateTimeField(blank=True, null=True, verbose_name='期望临时权限失效时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_approvals', to='iam.principal', verbose_name='受益主体')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_approval_requests', to='iam.principal', verbose_name='撤回主体')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='tenancy.environment', verbose_name='环境')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='tenancy.project', verbose_name='项目')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to='iam.principal', verbose_name='申请主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '审批请求',
                'verbose_name_plural': '审批请求',
                'db_table': 'sf_approval_request',
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVE', '批准'), ('REJECT', '拒绝')], max_length=16, verbose_name='审批结果')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('authority_snapshot', models.JSONField(blank=True, default=dict, help_text='保存作出审批决定时 authority checker 的可解释证据。', verbose_name='审批 authority evidence')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审批时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to='iam.principal', verbose_name='审批主体')),
                ('approval_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='elevation.approvalrequest', verbose_name='审批请求')),
            ],
            options={
                'verbose_name': '审批决定',
                'verbose_name_plural': '审批决定',
                'db_table': 'sf_approval_decision',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequestPrivilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privilege_links', to='elevation.approvalrequest', verbose_name='审批请求')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_request_links', to='iam.privilege', verbose_name='请求权限')),
            ],
            options={
                'verbose_name': '审批请求权限',
                'verbose_name_plural': '审批请求权限',
                'db_table': 'sf_approval_request_privilege',
            },
        ),
        migrations.CreateModel(
            name='DelegationGrant',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='作用域类型')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='失效时间')),
                ('reason', models.TextField(verbose_name='委托原因')),
                ('authority_snapshot', models.JSONField(blank=True, default=dict, help_text='仅用于解释创建时校验，不成为永久权限来源；resolver 必须重新验证 delegator authority。', verbose_name='创建时 authority evidence')),
                ('authority_checked_at', models.DateTimeField(verbose_name='创建时 authority 校验时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_delegation_grants', to='iam.principal', verbose_name='创建主体')),
                ('delegatee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_delegations', to='iam.principal', verbose_name='受托主体')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_delegations', to='iam.principal', verbose_name='委托主体')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegation_grants', to='tenancy.environment', verbose_name='环境')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegation_grants', to='tenancy.project', verbose_name='项目')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_delegation_grants', to='iam.principal', verbose_name='撤销主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_grants', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegation_grants', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '权限委托',
                'verbose_name_plural': '权限委托',
                'db_table': 'sf_delegation_grant',
            },
        ),
        migrations.CreateModel(
            name='DelegationGrantPrivilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privilege_links', to='elevation.delegationgrant', verbose_name='委托授权')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_links', to='iam.privilege', verbose_name='委托权限')),
            ],
            options={
                'verbose_name': '委托权限',
                'verbose_name_plural': '委托权限',
                'db_table': 'sf_delegation_grant_privilege',
            },
        ),
        migrations.CreateModel(
            name='PermissionBoundary',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='作用域类型')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('reason', models.TextField(verbose_name='设置原因')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_permission_boundaries', to='iam.principal', verbose_name='创建主体')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_boundaries', to='tenancy.environment', verbose_name='环境')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_boundaries', to='iam.principal', verbose_name='受限主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_boundaries', to='tenancy.project', verbose_name='项目')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_permission_boundaries', to='iam.principal', verbose_name='撤销主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_boundaries', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_boundaries', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '权限边界',
                'verbose_name_plural': '权限边界',
                'db_table': 'sf_permission_boundary',
            },
        ),
        migrations.CreateModel(
            name='PermissionBoundaryPrivilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privilege_links', to='elevation.permissionboundary', verbose_name='权限边界')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_boundary_links', to='iam.privilege', verbose_name='允许权限')),
            ],
            options={
                'verbose_name': '权限边界动作',
                'verbose_name_plural': '权限边界动作',
                'db_table': 'sf_permission_boundary_privilege',
            },
        ),
        migrations.CreateModel(
            name='TemporaryAccessGrant',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('mode', models.CharField(choices=[('JIT', '即时临时提升'), ('BREAK_GLASS', '紧急访问')], max_length=16, verbose_name='提升模式')),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='作用域类型')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='失效时间')),
                ('reason', models.TextField(verbose_name='提升原因')),
                ('emergency_reason', models.TextField(blank=True, default='', verbose_name='紧急访问原因')),
                ('notification_required', models.BooleanField(default=False, verbose_name='必须触发安全通知')),
                ('idempotency_key', models.CharField(blank=True, default='', help_text='BREAK_GLASS 必填；JIT 通过 source ApprovalRequest 自带幂等 identity。', max_length=160, validators=[django.core.validators.RegexValidator(message='idempotency_key 只能包含字母、数字、._:/-，且必须以字母或数字开头。', regex='^[A-Za-z0-9][A-Za-z0-9_.:/-]{0,159}$')], verbose_name='激活幂等键')),
                ('activation_authority_snapshot', models.JSONField(blank=True, default=dict, help_text='Break-glass 激活时保存 authority checker evidence；JIT 通常为空。', verbose_name='激活 authority evidence')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('activated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activated_temporary_access_grants', to='iam.principal', verbose_name='激活主体')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_access_grants', to='iam.principal', verbose_name='受益主体')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_access_grants', to='tenancy.environment', verbose_name='环境')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_access_grants', to='tenancy.project', verbose_name='项目')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_temporary_access_grants', to='iam.principal', verbose_name='撤销主体')),
                ('source_approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_access_grants', to='elevation.approvalrequest', verbose_name='来源审批')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_access_grants', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_access_grants', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '临时提升授权',
                'verbose_name_plural': '临时提升授权',
                'db_table': 'sf_temporary_access_grant',
            },
        ),
        migrations.CreateModel(
            name='TemporaryAccessGrantPrivilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privilege_links', to='elevation.temporaryaccessgrant', verbose_name='临时提升授权')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_access_links', to='iam.privilege', verbose_name='临时权限')),
            ],
            options={
                'verbose_name': '临时提升权限',
                'verbose_name_plural': '临时提升权限',
                'db_table': 'sf_temporary_access_privilege',
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'beneficiary', 'status'], name='sf_apreq_benef_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'requester', 'status'], name='sf_apreq_req_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'purpose', 'status'], name='sf_apreq_purp_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['expires_at'], name='sf_apreq_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('resource_id__isnull', True), ('resource_kind', ''), ('target_type', 'ENVIRONMENT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('resource_id__isnull', False), ('target_type', 'RESOURCE'), ('workspace__isnull', True), models.Q(('resource_kind', ''), _negated=True)), _connector='OR'), name='sf_apreq_target_ck'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('requested_at'))), name='sf_apreq_expiry_ck'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_valid_until__isnull', True), ('requested_valid_until__gt', models.F('requested_at')), _connector='OR'), name='sf_apreq_valid_ck'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sf_apreq_reason_ck'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'CANCELLED')), models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='sf_apreq_cancel_ck'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['approver', 'decided_at'], name='sf_apdec_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequestprivilege',
            index=models.Index(fields=['privilege'], name='sf_apreq_priv_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequestprivilege',
            constraint=models.UniqueConstraint(fields=('approval_request', 'privilege'), name='sf_apreq_priv_uniq'),
        ),
        migrations.AddIndex(
            model_name='delegationgrant',
            index=models.Index(fields=['tenant', 'delegator', 'status'], name='sf_deleg_from_idx'),
        ),
        migrations.AddIndex(
            model_name='delegationgrant',
            index=models.Index(fields=['tenant', 'delegatee', 'status'], name='sf_deleg_to_idx'),
        ),
        migrations.AddIndex(
            model_name='delegationgrant',
            index=models.Index(fields=['valid_until'], name='sf_deleg_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='delegationgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_deleg_scope_ck'),
        ),
        migrations.AddConstraint(
            model_name='delegationgrant',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='sf_deleg_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='delegationgrant',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sf_deleg_reason_ck'),
        ),
        migrations.AddConstraint(
            model_name='delegationgrant',
            constraint=models.CheckConstraint(condition=models.Q(('delegator', models.F('delegatee')), _negated=True), name='sf_deleg_distinct_ck'),
        ),
        migrations.AddConstraint(
            model_name='delegationgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='sf_deleg_revoke_ck'),
        ),
        migrations.AddIndex(
            model_name='delegationgrantprivilege',
            index=models.Index(fields=['privilege'], name='sf_deleg_priv_idx'),
        ),
        migrations.AddConstraint(
            model_name='delegationgrantprivilege',
            constraint=models.UniqueConstraint(fields=('delegation', 'privilege'), name='sf_deleg_priv_uniq'),
        ),
        migrations.AddIndex(
            model_name='permissionboundary',
            index=models.Index(fields=['tenant', 'principal', 'status'], name='sf_pbound_princ_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionboundary',
            index=models.Index(fields=['tenant', 'scope_type', 'status'], name='sf_pbound_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissionboundary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_pbound_scope_ck'),
        ),
        migrations.AddConstraint(
            model_name='permissionboundary',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_pbound_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='permissionboundary',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sf_pbound_reason_ck'),
        ),
        migrations.AddConstraint(
            model_name='permissionboundary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='sf_pbound_revoke_ck'),
        ),
        migrations.AddIndex(
            model_name='permissionboundaryprivilege',
            index=models.Index(fields=['privilege'], name='sf_pbound_priv_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissionboundaryprivilege',
            constraint=models.UniqueConstraint(fields=('boundary', 'privilege'), name='sf_pbound_priv_uniq'),
        ),
        migrations.AddIndex(
            model_name='temporaryaccessgrant',
            index=models.Index(fields=['tenant', 'beneficiary', 'status'], name='sf_tmpgrant_ben_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryaccessgrant',
            index=models.Index(fields=['valid_until'], name='sf_tmpgrant_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryaccessgrant',
            index=models.Index(fields=['tenant', 'mode', 'status'], name='sf_tmpgrant_mode_idx'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_tmpgrant_scope_ck'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='sf_tmpgrant_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sf_tmpgrant_reason_ck'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('emergency_reason', ''), ('idempotency_key', ''), ('mode', 'JIT'), ('source_approval_request__isnull', False)), models.Q(('mode', 'BREAK_GLASS'), ('notification_required', True), models.Q(('emergency_reason', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), _connector='OR'), name='sf_tmpgrant_mode_ck'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('source_approval_request__isnull', False)), fields=('source_approval_request',), name='sf_tmpgrant_apreq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'BREAK_GLASS')), fields=('tenant', 'activated_by', 'idempotency_key'), name='sf_tmpgrant_bg_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='sf_tmpgrant_revoke_ck'),
        ),
        migrations.AddIndex(
            model_name='temporaryaccessgrantprivilege',
            index=models.Index(fields=['privilege'], name='sf_tmpgrant_priv_idx'),
        ),
        migrations.AddConstraint(
            model_name='temporaryaccessgrantprivilege',
            constraint=models.UniqueConstraint(fields=('grant', 'privilege'), name='sf_tmpgrant_priv_uniq'),
        ),
    ]
