# Generated by Django 5.2.17 on 2026-08-29 17:10

import django.db.models.deletion
import spatial_fabric.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_enable_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='租户名称')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='租户标识')),
                ('status', models.CharField(choices=[('PROVISIONING', '开通中'), ('ACTIVE', '正常'), ('SUSPENDED', '已暂停'), ('OFFBOARDING', '下线处理中'), ('CLOSED', '已关闭')], default='PROVISIONING', max_length=24, verbose_name='状态')),
                ('default_locale', models.CharField(default='zh-hans', max_length=32, verbose_name='默认语言')),
                ('default_timezone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='默认时区')),
                ('data_residency_policy', models.JSONField(blank=True, default=dict, verbose_name='数据驻留策略')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'sf_tenant',
                'indexes': [models.Index(fields=['status'], name='sf_tenant_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='工作空间名称')),
                ('slug', models.SlugField(max_length=80, verbose_name='工作空间标识')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('READ_ONLY', '只读'), ('ARCHIVED', '已归档'), ('TRASHED', '回收站')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '工作空间',
                'verbose_name_plural': '工作空间',
                'db_table': 'sf_workspace',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('slug', models.SlugField(max_length=80, verbose_name='项目标识')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '进行中'), ('ON_HOLD', '暂停'), ('COMPLETED', '已完成'), ('ARCHIVED', '已归档'), ('TRASHED', '回收站')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='tenancy.workspace', verbose_name='所属工作空间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'sf_project',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=120, verbose_name='环境名称')),
                ('slug', models.SlugField(max_length=64, verbose_name='环境标识')),
                ('environment_type', models.CharField(choices=[('DEVELOPMENT', '开发'), ('TEST', '测试'), ('STAGING', '预发布'), ('PRODUCTION', '生产'), ('SANDBOX', '沙箱')], max_length=20, verbose_name='环境类型')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('FROZEN', '冻结'), ('ARCHIVED', '已归档')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('protection_level', models.CharField(choices=[('NORMAL', '普通'), ('PROTECTED', '受保护'), ('CRITICAL', '关键')], default='NORMAL', max_length=20, verbose_name='保护级别')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='tenancy.project', verbose_name='所属项目')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'sf_environment',
                'indexes': [models.Index(fields=['tenant', 'status'], name='sf_env_tenant_status_idx'), models.Index(fields=['project', 'environment_type'], name='sf_env_proj_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'slug'), name='sf_env_project_slug_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['tenant', 'status'], name='sf_ws_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['tenant', 'name'], name='sf_ws_tenant_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='sf_ws_tenant_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'status'], name='sf_proj_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='sf_proj_ws_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='sf_project_ws_slug_uniq'),
        ),
    ]
