# Generated by Django 5.2.17 on 2026-08-29 17:10

import django.db.models.deletion
import django.utils.timezone
import spatial_fabric.common.ids
import spatial_fabric.iam.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', spatial_fabric.iam.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('principal_type', models.CharField(choices=[('HUMAN_USER', '人员'), ('SERVICE_ACCOUNT', '服务账户'), ('AGENT', '智能体'), ('EXTERNAL_APPLICATION', '外部应用'), ('FEDERATED', '联合身份')], max_length=32, verbose_name='主体类型')),
                ('status', models.CharField(choices=[('INVITED', '待激活'), ('ACTIVE', '正常'), ('SUSPENDED', '已暂停'), ('LOCKED', '已锁定'), ('DEPROVISIONED', '已注销')], default='ACTIVE', max_length=24, verbose_name='状态')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principal', to=settings.AUTH_USER_MODEL, verbose_name='登录账户')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principals', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '权限主体',
                'verbose_name_plural': '权限主体',
                'db_table': 'sf_principal',
                'indexes': [models.Index(fields=['tenant', 'status'], name='sf_princ_tenant_status_idx'), models.Index(fields=['tenant', 'principal_type'], name='sf_princ_tenant_type_idx')],
            },
        ),
    ]
