# Generated by Django 5.2.17 on 2026-08-29 18:23

import django.core.validators
import django.db.models.deletion
import spatial_fabric.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='组名称')),
                ('slug', models.SlugField(max_length=100, verbose_name='组标识')),
                ('group_type', models.CharField(choices=[('SECURITY', '安全组'), ('COLLABORATION', '协作组')], default='SECURITY', max_length=24, verbose_name='组类型')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('SUSPENDED', '已暂停'), ('ARCHIVED', '已归档')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_principal_groups', to='iam.principal', verbose_name='创建主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='principal_groups', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '权限组',
                'verbose_name_plural': '权限组',
                'db_table': 'sf_group',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('SUSPENDED', '已暂停')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_group_memberships', to='iam.principal', verbose_name='添加主体')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='iam.group', verbose_name='权限组')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='iam.principal', verbose_name='成员主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '组成员关系',
                'verbose_name_plural': '组成员关系',
                'db_table': 'sf_group_membership',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Privilege key 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,79}$')], verbose_name='权限键')),
                ('name', models.CharField(max_length=120, verbose_name='权限名称')),
                ('category', models.CharField(choices=[('READ', '读取'), ('WRITE', '写入'), ('EXECUTE', '执行'), ('GOVERNANCE', '治理'), ('ADMIN', '管理'), ('SECRET', '密钥')], max_length=20, verbose_name='类别')),
                ('risk_level', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '关键')], default='LOW', max_length=16, verbose_name='风险等级')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('DEPRECATED', '已弃用')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('system_managed', models.BooleanField(default=True, help_text='系统管理的 Privilege 只能通过受控 migration/package registration 变更。', verbose_name='系统管理')),
            ],
            options={
                'verbose_name': '权限动作',
                'verbose_name_plural': '权限动作',
                'db_table': 'sf_privilege',
                'indexes': [models.Index(fields=['status', 'category'], name='sf_priv_status_cat_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('key', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Privilege key 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,79}$')], verbose_name='角色键')),
                ('name', models.CharField(max_length=160, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('DEPRECATED', '已弃用')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统角色')),
                ('is_assignable', models.BooleanField(default=True, verbose_name='允许分配')),
                ('allowed_scope_types', models.JSONField(blank=True, default=list, help_text='空列表表示不额外限制；非空时只能包含 TENANT/WORKSPACE/PROJECT/ENVIRONMENT。', verbose_name='允许的作用域类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_role_definitions', to='iam.principal', verbose_name='创建主体')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_definitions', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '角色定义',
                'verbose_name_plural': '角色定义',
                'db_table': 'sf_role_definition',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='作用域类型')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='B1 仅允许 schema-validated 的低复杂度条件；完整 ABAC 留给 B2 Policy。', verbose_name='附加条件')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='tenancy.environment', verbose_name='环境作用域')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_role_assignments', to='iam.principal', verbose_name='授权主体')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='iam.group', verbose_name='被授权组')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_role_assignments', to='iam.principal', verbose_name='被授权主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='tenancy.project', verbose_name='项目作用域')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='tenancy.workspace', verbose_name='工作空间作用域')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='iam.roledefinition', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色分配',
                'verbose_name_plural': '角色分配',
                'db_table': 'sf_role_assignment',
            },
        ),
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_privileges', to='iam.privilege', verbose_name='权限动作')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_privileges', to='iam.roledefinition', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'sf_role_privilege',
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tenant', 'status'], name='sf_group_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tenant', 'group_type'], name='sf_group_tenant_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='sf_group_tenant_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['tenant', 'principal', 'status'], name='sf_gmem_princ_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['tenant', 'group', 'status'], name='sf_gmem_group_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'principal'), name='sf_groupmem_group_princ_uniq'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_groupmem_valid_window_ck'),
        ),
        migrations.AddIndex(
            model_name='roledefinition',
            index=models.Index(fields=['tenant', 'status'], name='sf_role_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='roledefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('key',), name='sf_role_platform_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='roledefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'key'), name='sf_role_tenant_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['tenant', 'principal', 'status'], name='sf_rassign_princ_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['tenant', 'group', 'status'], name='sf_rassign_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['workspace', 'status'], name='sf_rassign_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['project', 'status'], name='sf_rassign_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['environment', 'status'], name='sf_rassign_env_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('principal__isnull', False)), models.Q(('group__isnull', False), ('principal__isnull', True)), _connector='OR'), name='sf_roleassign_subject_xor_ck'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_roleassign_scope_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_roleassign_valid_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'principal', 'group', 'role', 'scope_type', 'workspace', 'project', 'environment'), name='sf_roleassign_identity_uniq', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='roleprivilege',
            index=models.Index(fields=['role'], name='sf_rolepriv_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleprivilege',
            constraint=models.UniqueConstraint(fields=('role', 'privilege'), name='sf_rolepriv_pair_uniq'),
        ),
    ]
