# Generated by Django 5.2.17 on 2026-08-30 03:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import spatial_fabric.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_seed_core_privileges'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('metric_key', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='商业控制 key 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='指标键')),
                ('unit', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='unit 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,31}$')], verbose_name='单位')),
                ('subject_type', models.CharField(choices=[('TENANT', '租户'), ('PRINCIPAL', '主体')], max_length=16, verbose_name='主体类型')),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='作用域类型')),
                ('measurement_type', models.CharField(choices=[('GAUGE', '当前占用'), ('CONCURRENCY', '并发占用'), ('CONSUMPTION', '累计消费')], max_length=16, verbose_name='计量类型')),
                ('limit_value', models.PositiveBigIntegerField(verbose_name='限制值')),
                ('window_type', models.CharField(choices=[('NONE', '无时间窗口'), ('CALENDAR_DAY', '自然日'), ('CALENDAR_MONTH', '自然月')], max_length=24, verbose_name='窗口类型')),
                ('enforcement_mode', models.CharField(choices=[('OBSERVE', '仅观测'), ('SOFT', '软限制'), ('HARD', '硬限制')], default='HARD', max_length=16, verbose_name='执行模式')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotas', to='iam.principal', verbose_name='创建主体')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='tenancy.environment', verbose_name='环境')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='iam.principal', verbose_name='主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='tenancy.project', verbose_name='项目')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_quotas', to='iam.principal', verbose_name='撤销主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '技术配额',
                'verbose_name_plural': '技术配额',
                'db_table': 'sf_quota',
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('window_start', models.DateTimeField(blank=True, null=True, verbose_name='窗口开始')),
                ('window_end', models.DateTimeField(blank=True, null=True, verbose_name='窗口结束')),
                ('consumed_value', models.PositiveBigIntegerField(default=0, verbose_name='已消费')),
                ('reserved_value', models.PositiveBigIntegerField(default=0, verbose_name='已预留')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='commercial.quota', verbose_name='配额')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_counters', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '使用计数器',
                'verbose_name_plural': '使用计数器',
                'db_table': 'sf_usage_counter',
            },
        ),
        migrations.CreateModel(
            name='UsageReservation',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('metric_key', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='商业控制 key 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='指标键')),
                ('measurement_type', models.CharField(choices=[('GAUGE', '当前占用'), ('CONCURRENCY', '并发占用'), ('CONSUMPTION', '累计消费')], max_length=16, verbose_name='计量类型')),
                ('unit', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='unit 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,31}$')], verbose_name='单位')),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='操作作用域')),
                ('amount', models.PositiveBigIntegerField(verbose_name='请求量')),
                ('idempotency_key', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='idempotency_key 只能包含字母、数字、._:/-，且必须以字母或数字开头。', regex='^[A-Za-z0-9][A-Za-z0-9_.:/-]{0,159}$')], verbose_name='幂等键')),
                ('status', models.CharField(choices=[('RESERVED', '已预留'), ('COMMITTED', '已提交'), ('RELEASED', '已释放'), ('EXPIRED', '已过期')], default='RESERVED', max_length=16, verbose_name='状态')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预留时间')),
                ('expires_at', models.DateTimeField(verbose_name='预留失效时间')),
                ('committed_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_reservations', to='tenancy.environment', verbose_name='环境')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_reservations', to='iam.principal', verbose_name='消费主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_reservations', to='tenancy.project', verbose_name='项目')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_reservations', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_reservations', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '使用预留',
                'verbose_name_plural': '使用预留',
                'db_table': 'sf_usage_reservation',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='商业控制 key 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='指标键')),
                ('measurement_type', models.CharField(choices=[('GAUGE', '当前占用'), ('CONCURRENCY', '并发占用'), ('CONSUMPTION', '累计消费')], max_length=16, verbose_name='计量类型')),
                ('unit', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='unit 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,31}$')], verbose_name='单位')),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='操作作用域')),
                ('event_type', models.CharField(choices=[('CONSUME', '消费'), ('RELEASE', '释放')], max_length=16, verbose_name='事件类型')),
                ('amount', models.PositiveBigIntegerField(verbose_name='数量')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记账时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='tenancy.environment', verbose_name='环境')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='iam.principal', verbose_name='消费主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='tenancy.project', verbose_name='项目')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='tenancy.workspace', verbose_name='工作空间')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='commercial.usagereservation', verbose_name='来源预留')),
            ],
            options={
                'verbose_name': '使用事实',
                'verbose_name_plural': '使用事实',
                'db_table': 'sf_usage_record',
            },
        ),
        migrations.CreateModel(
            name='UsageReservationQuota',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='预留量')),
                ('limit_snapshot', models.PositiveBigIntegerField(verbose_name='限制值快照')),
                ('enforcement_mode_snapshot', models.CharField(choices=[('OBSERVE', '仅观测'), ('SOFT', '软限制'), ('HARD', '硬限制')], max_length=16, verbose_name='执行模式快照')),
                ('consumed_value_snapshot', models.PositiveBigIntegerField(verbose_name='决策时已消费值快照')),
                ('reserved_value_snapshot', models.PositiveBigIntegerField(verbose_name='决策时已预留值快照')),
                ('projected_value_snapshot', models.PositiveBigIntegerField(verbose_name='决策时 projected 值')),
                ('exceeded_snapshot', models.BooleanField(default=False, verbose_name='决策时是否超限')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_links', to='commercial.usagecounter', verbose_name='计数器')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_links', to='commercial.quota', verbose_name='命中的配额')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_links', to='commercial.usagereservation', verbose_name='使用预留')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_reservation_quota_links', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '使用预留配额证据',
                'verbose_name_plural': '使用预留配额证据',
                'db_table': 'sf_usage_reservation_quota',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('budget_key', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='商业控制 key 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='预算键')),
                ('name', models.CharField(max_length=200, verbose_name='预算名称')),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='作用域类型')),
                ('currency_code', models.CharField(help_text='ISO 4217 三字母代码。', max_length=3, validators=[django.core.validators.RegexValidator(message='currency_code 必须是三个大写 ASCII 字母，例如 CNY、USD。', regex='^[A-Z]{3}$')], verbose_name='币种')),
                ('amount_limit', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='预算上限')),
                ('window_type', models.CharField(choices=[('CALENDAR_MONTH', '自然月'), ('CALENDAR_YEAR', '自然年'), ('FIXED_TERM', '固定合同期')], max_length=24, verbose_name='预算周期')),
                ('enforcement_mode', models.CharField(choices=[('OBSERVE', '仅观测'), ('SOFT', '软限制'), ('HARD', '硬限制')], default='SOFT', max_length=16, verbose_name='执行模式')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budgets', to='iam.principal', verbose_name='创建主体')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='tenancy.environment', verbose_name='环境')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='tenancy.project', verbose_name='项目')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_budgets', to='iam.principal', verbose_name='撤销主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '成本预算',
                'verbose_name_plural': '成本预算',
                'db_table': 'sf_budget',
                'indexes': [models.Index(fields=['tenant', 'budget_key', 'status'], name='sf_budget_key_idx'), models.Index(fields=['project', 'status'], name='sf_budget_proj_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_budget_scope_shape_ck'), models.CheckConstraint(condition=models.Q(('amount_limit__gt', 0)), name='sf_budget_amount_ck'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_budget_valid_window_ck'), models.CheckConstraint(condition=models.Q(models.Q(('valid_from__isnull', False), ('valid_until__isnull', False), ('window_type', 'FIXED_TERM')), ('window_type__in', ['CALENDAR_MONTH', 'CALENDAR_YEAR']), _connector='OR'), name='sf_budget_term_shape_ck'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='sf_budget_revoke_shape_ck')],
            },
        ),
        migrations.CreateModel(
            name='EntitlementGrant',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('entitlement_key', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='商业控制 key 必须以小写字母开头，且只能包含小写字母、数字、._:-。', regex='^[a-z][a-z0-9_.:-]{0,159}$')], verbose_name='许可键')),
                ('subject_type', models.CharField(choices=[('TENANT', '租户'), ('PRINCIPAL', '主体')], max_length=16, verbose_name='主体类型')),
                ('scope_type', models.CharField(choices=[('TENANT', '租户'), ('WORKSPACE', '工作空间'), ('PROJECT', '项目'), ('ENVIRONMENT', '环境')], max_length=16, verbose_name='作用域类型')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('REVOKED', '已撤销')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_grants', to='tenancy.environment', verbose_name='环境')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_entitlement_grants', to='iam.principal', verbose_name='授权主体')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_grants', to='iam.principal', verbose_name='主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_grants', to='tenancy.project', verbose_name='项目')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_entitlement_grants', to='iam.principal', verbose_name='撤销主体')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_grants', to='tenancy.tenant', verbose_name='所属租户')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_grants', to='tenancy.workspace', verbose_name='工作空间')),
            ],
            options={
                'verbose_name': '商业许可授权',
                'verbose_name_plural': '商业许可授权',
                'db_table': 'sf_entitlement_grant',
                'indexes': [models.Index(fields=['tenant', 'entitlement_key', 'status'], name='sf_ent_key_status_idx'), models.Index(fields=['tenant', 'principal', 'status'], name='sf_ent_princ_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('principal__isnull', True), ('subject_type', 'TENANT')), models.Q(('principal__isnull', False), ('subject_type', 'PRINCIPAL')), _connector='OR'), name='sf_ent_subject_shape_ck'), models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_ent_scope_shape_ck'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_ent_valid_window_ck'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='sf_ent_revoke_shape_ck')],
            },
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['tenant', 'metric_key', 'status'], name='sf_quota_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['tenant', 'principal', 'status'], name='sf_quota_princ_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['project', 'metric_key', 'status'], name='sf_quota_proj_idx'),
        ),
        migrations.AddConstraint(
            model_name='quota',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('principal__isnull', True), ('subject_type', 'TENANT')), models.Q(('principal__isnull', False), ('subject_type', 'PRINCIPAL')), _connector='OR'), name='sf_quota_subject_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='quota',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_quota_scope_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='quota',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('measurement_type__in', ['GAUGE', 'CONCURRENCY']), ('window_type', 'NONE')), models.Q(('measurement_type', 'CONSUMPTION'), ('window_type__in', ['CALENDAR_DAY', 'CALENDAR_MONTH'])), _connector='OR'), name='sf_quota_measure_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='quota',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='sf_quota_valid_window_ck'),
        ),
        migrations.AddConstraint(
            model_name='quota',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'ACTIVE')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'REVOKED')), _connector='OR'), name='sf_quota_revoke_shape_ck'),
        ),
        migrations.AddIndex(
            model_name='usagecounter',
            index=models.Index(fields=['tenant', 'quota'], name='sf_ucounter_quota_idx'),
        ),
        migrations.AddIndex(
            model_name='usagecounter',
            index=models.Index(fields=['window_end'], name='sf_ucounter_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('window_end__isnull', True), ('window_start__isnull', True)), models.Q(('window_end__gt', models.F('window_start')), ('window_end__isnull', False), ('window_start__isnull', False)), _connector='OR'), name='sf_ucounter_window_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.UniqueConstraint(fields=('quota', 'window_start', 'window_end'), name='sf_ucounter_identity_uniq', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='usagereservation',
            index=models.Index(fields=['tenant', 'metric_key', 'status', 'expires_at'], name='sf_ures_metric_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='usagereservation',
            index=models.Index(fields=['tenant', 'principal', 'status'], name='sf_ures_princ_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagereservation',
            constraint=models.UniqueConstraint(fields=('tenant', 'principal', 'idempotency_key'), name='sf_ures_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usagereservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sf_ures_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='usagereservation',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('reserved_at'))), name='sf_ures_expiry_ck'),
        ),
        migrations.AddConstraint(
            model_name='usagereservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_ures_scope_shape_ck'),
        ),
        migrations.AddConstraint(
            model_name='usagereservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('committed_at__isnull', True), ('status', 'RESERVED')), models.Q(('closed_at__isnull', True), ('committed_at__isnull', False), ('status', 'COMMITTED')), models.Q(('closed_at__isnull', False), ('status', 'RELEASED')), models.Q(('closed_at__isnull', False), ('committed_at__isnull', True), ('status', 'EXPIRED')), _connector='OR'), name='sf_ures_status_shape_ck'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['tenant', 'metric_key', 'recorded_at'], name='sf_urecord_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['tenant', 'principal', 'recorded_at'], name='sf_urecord_princ_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('reservation', 'event_type'), name='sf_urecord_res_event_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sf_urecord_amount_ck'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'TENANT'), ('workspace__isnull', True)), models.Q(('environment__isnull', True), ('project__isnull', True), ('scope_type', 'WORKSPACE'), ('workspace__isnull', False)), models.Q(('environment__isnull', True), ('project__isnull', False), ('scope_type', 'PROJECT'), ('workspace__isnull', True)), models.Q(('environment__isnull', False), ('project__isnull', True), ('scope_type', 'ENVIRONMENT'), ('workspace__isnull', True)), _connector='OR'), name='sf_urecord_scope_shape_ck'),
        ),
        migrations.AddIndex(
            model_name='usagereservationquota',
            index=models.Index(fields=['tenant', 'quota'], name='sf_uresquota_quota_idx'),
        ),
        migrations.AddIndex(
            model_name='usagereservationquota',
            index=models.Index(fields=['counter'], name='sf_uresquota_counter_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagereservationquota',
            constraint=models.UniqueConstraint(fields=('reservation', 'quota'), name='sf_uresquota_res_quota_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usagereservationquota',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sf_uresquota_amount_ck'),
        ),
    ]
