# Generated by Django 5.2.17 on 2026-08-29 17:10

import django.db.models.deletion
import spatial_fabric.common.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('asset_type', models.CharField(help_text='使用稳定、可扩展的 namespaced key，例如 dataset、map、geophysics.modelpack。', max_length=80, verbose_name='资产类型')),
                ('traits', models.JSONField(blank=True, default=list, help_text='仅保存诸如 spatial/executable/temporal 等 trait key；不能代替关系表。', verbose_name='能力特征')),
                ('name', models.CharField(max_length=240, verbose_name='资产名称')),
                ('slug', models.SlugField(max_length=100, verbose_name='资产标识')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('DEPRECATED', '已弃用'), ('ARCHIVED', '已归档'), ('TRASHED', '回收站'), ('BLOCKED', '已阻止')], default='ACTIVE', max_length=20, verbose_name='生命周期状态')),
                ('classification', models.CharField(choices=[('PUBLIC', '公开'), ('INTERNAL', '内部'), ('CONFIDENTIAL', '机密'), ('RESTRICTED', '严格受限')], default='INTERNAL', max_length=20, verbose_name='数据/资源分级')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'sf_asset',
            },
        ),
        migrations.CreateModel(
            name='AssetAlias',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('alias', models.SlugField(max_length=64, verbose_name='别名')),
            ],
            options={
                'verbose_name': '资产版本别名',
                'verbose_name_plural': '资产版本别名',
                'db_table': 'sf_asset_alias',
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_seq', models.PositiveBigIntegerField(verbose_name='内部版本序号')),
                ('version_label', models.CharField(blank=True, max_length=80, verbose_name='版本标签')),
                ('schema_ref', models.CharField(blank=True, help_text='例如内部 JSON Schema 的稳定 URI/key。', max_length=240, verbose_name='Schema 引用')),
                ('schema_version', models.CharField(blank=True, max_length=80, verbose_name='Schema 版本')),
                ('spec', models.JSONField(default=dict, verbose_name='版本规范')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='版本元数据')),
                ('content_hash', models.CharField(blank=True, help_text='发布时对规范化 spec、关键依赖和 Artifact digest 计算；算法由发布服务统一决定。', max_length=128, verbose_name='内容指纹')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('VALIDATING', '验证中'), ('READY', '就绪'), ('PUBLISHED', '已发布'), ('DEPRECATED', '已弃用'), ('ARCHIVED', '已归档'), ('QUARANTINED', '隔离'), ('REJECTED', '拒绝发布')], default='DRAFT', max_length=20, verbose_name='版本状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('deprecated_at', models.DateTimeField(blank=True, null=True, verbose_name='弃用时间')),
            ],
            options={
                'verbose_name': '资产版本',
                'verbose_name_plural': '资产版本',
                'db_table': 'sf_asset_version',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveBigIntegerField(default=0)),
                ('distribution_type', models.CharField(choices=[('FILE', '文件'), ('DATABASE', '数据库'), ('OBJECT', '对象存储'), ('VECTOR', '矢量'), ('RASTER', '栅格'), ('MULTIDIMENSIONAL', '多维科学数据'), ('TILE_ARCHIVE', '瓦片归档'), ('WEB_SERVICE', 'Web 服务'), ('STREAM', '实时流'), ('MODEL_ENDPOINT', '模型端点'), ('THREE_D', '三维'), ('POINT_CLOUD', '点云'), ('CATALOG', '目录')], max_length=24, verbose_name='分发类型')),
                ('format', models.CharField(blank=True, help_text='例如 postgis、geoparquet、cog、zarr、pmtiles、wms、ogc_features。', max_length=80, verbose_name='格式')),
                ('protocol', models.CharField(blank=True, max_length=80, verbose_name='协议')),
                ('status', models.CharField(choices=[('PENDING', '待生成'), ('AVAILABLE', '可用'), ('DEGRADED', '降级'), ('UNAVAILABLE', '不可用'), ('RETIRED', '已退役')], default='PENDING', max_length=20, verbose_name='状态')),
                ('access_mode', models.CharField(choices=[('DIRECT', '直接访问'), ('SIGNED', '签名访问'), ('PROXIED', '平台代理'), ('INTERNAL', '仅内部')], default='PROXIED', max_length=16, verbose_name='访问模式')),
                ('mutability', models.CharField(choices=[('IMMUTABLE_CONTENT', '不可变内容'), ('MUTABLE_ENDPOINT', '可变端点'), ('EPHEMERAL', '临时'), ('LIVE', '实时')], default='IMMUTABLE_CONTENT', max_length=24, verbose_name='可变性')),
                ('service_deployment_ref', models.UUIDField(blank=True, null=True, verbose_name='服务部署引用')),
                ('external_location_ref', models.TextField(blank=True, help_text='外部资源的受控引用；不得在这里存明文 Secret。', verbose_name='外部位置引用')),
                ('spatial_metadata', models.JSONField(blank=True, default=dict, verbose_name='空间技术元数据')),
                ('temporal_metadata', models.JSONField(blank=True, default=dict, verbose_name='时间技术元数据')),
                ('technical_metadata', models.JSONField(blank=True, default=dict, help_text='必须是 provider-neutral 或 namespaced 扩展；核心关系不得藏在 JSONB。', verbose_name='扩展技术元数据')),
            ],
            options={
                'verbose_name': '分发形态',
                'verbose_name_plural': '分发形态',
                'db_table': 'sf_distribution',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=spatial_fabric.common.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest_algorithm', models.CharField(default='sha256', max_length=24, verbose_name='摘要算法')),
                ('digest', models.CharField(max_length=256, verbose_name='内容摘要')),
                ('media_type', models.CharField(blank=True, max_length=160, verbose_name='媒体类型')),
                ('size', models.PositiveBigIntegerField(verbose_name='字节数')),
                ('filename', models.CharField(blank=True, max_length=512, verbose_name='原始/建议文件名')),
                ('storage_pool_ref', models.UUIDField(help_text='逻辑 StoragePool UUID；不是 MinIO/S3 厂商 ID。Phase A 先保留稳定引用。', verbose_name='存储池引用')),
                ('storage_object_ref', models.CharField(help_text='ObjectStore 内部不透明对象 key；API 不应直接向普通用户暴露真实存储路径。', max_length=1024, verbose_name='对象引用')),
                ('integrity_status', models.CharField(choices=[('PENDING', '待验证'), ('VERIFYING', '验证中'), ('AVAILABLE', '可用'), ('QUARANTINED', '隔离'), ('CORRUPTED', '损坏'), ('DELETING', '删除中'), ('DELETED', '已删除')], default='PENDING', max_length=20, verbose_name='完整性状态')),
                ('retention_class', models.CharField(blank=True, max_length=80, verbose_name='保留策略类别')),
                ('legal_hold', models.BooleanField(default=False, help_text='为 True 时禁止普通 GC/物理删除。', verbose_name='法律/合规保留')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='tenancy.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '制品',
                'verbose_name_plural': '制品',
                'db_table': 'sf_artifact',
            },
        ),
    ]
