# Generated by Django 5.2.17 on 2026-08-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('iam', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assets', to='iam.principal', verbose_name='创建主体'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_assets', to='iam.principal', verbose_name='资产责任主体'),
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tenancy.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='asset',
            name='steward_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stewarded_assets', to='iam.principal', verbose_name='资产治理责任人'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tenancy.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='asset',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tenancy.workspace', verbose_name='所属工作空间'),
        ),
        migrations.AddField(
            model_name='assetalias',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetalias',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_asset_aliases', to='iam.principal', verbose_name='最后更新主体'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assets.asset', verbose_name='所属资产'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_asset_versions', to='iam.principal', verbose_name='创建主体'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='replacement_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_versions', to='assets.assetversion', verbose_name='替代版本'),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='tenant',
            field=models.ForeignKey(help_text='显式冗余 tenant_id，便于 RLS、索引与跨租户防护；必须与 Asset.tenant 一致。', on_delete=django.db.models.deletion.PROTECT, related_name='asset_versions', to='tenancy.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='assetalias',
            name='target_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='assets.assetversion', verbose_name='目标版本'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='assets.artifact', verbose_name='制品'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='asset_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='assets.assetversion', verbose_name='所属资产版本'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='source_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_distributions', to='assets.distribution', verbose_name='来源分发'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='tenant',
            field=models.ForeignKey(help_text='显式冗余 tenant_id，便于 RLS、索引和安全查询。', on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='tenancy.tenant', verbose_name='所属租户'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['tenant', 'digest_algorithm', 'digest'], name='sf_artifact_digest_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['tenant', 'integrity_status'], name='sf_artifact_integrity_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('tenant', 'storage_pool_ref', 'storage_object_ref'), name='sf_artifact_storage_ref_uniq'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'asset_type', 'status'], name='sf_asset_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'project', 'status'], name='sf_asset_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'workspace', 'status'], name='sf_asset_ws_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('tenant', 'project', 'asset_type', 'slug'), name='sf_asset_project_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True), ('workspace__isnull', False)), fields=('tenant', 'workspace', 'asset_type', 'slug'), name='sf_asset_workspace_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True), ('workspace__isnull', True)), fields=('tenant', 'asset_type', 'slug'), name='sf_asset_tenant_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['tenant', 'status'], name='sf_assetver_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['asset', 'status'], name='sf_assetver_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['status', 'published_at'], name='sf_assetver_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.UniqueConstraint(fields=('asset', 'version_seq'), name='sf_assetver_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assetalias',
            constraint=models.UniqueConstraint(fields=('asset', 'alias'), name='sf_asset_alias_uniq'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['tenant', 'status'], name='sf_dist_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['asset_version', 'status'], name='sf_dist_assetver_status_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['distribution_type', 'format', 'status'], name='sf_dist_type_fmt_idx'),
        ),
    ]
